get http://localhost:8080/api/todo

###

post http://localhost:8080/api/todo
Content-Type: application/json

{
    "name":"test tambah todo",
    "status": ""
}

###
put http://localhost:8080/api/todo/6
Content-Type: application/json

{
    "name": "test edit to do edididididi",
    "status": true
}

###
delete http://localhost:8080/api/todo/15
Content-Type: application/json

