get http://localhost:8080/api/todo

###

post http://localhost:8080/api/todo
Content-Type: application/json

{
    "name":"test tambah todo",
    "status": ""
}

###
put http://localhost:8080/api/todo/5
Content-Type: application/json

{
    "name": "test edit to do",
    "status": true
}

###
delete http://localhost:8080/api/todo/7
Content-Type: application/json

